### ISSUE TITLE
Especificaciones SGE

### ISSUE THREAD

**Issue by miguelangelronda** [albertomorenogonzalez/FitnessGym#2]
Hola! no has indicado cómo vas a integrar los requisitos del módulo de Sistemas de Gestión Empresarial.

**Comment by albertomorenogonzalez** [comment]
Que es lo que debemos poner en el Readme ? Como cargamos el archivo CSV/JSON que sale de la base de datos y como lo pasamos a Power BI como aparece en los requisitos ?

**Comment by miguelangelronda** [comment]
Debes detallar qué harás en tu aplicación con Python+Pandas en baser a los requisitos.
