### ISSUE TITLE
Acceso al informe en PowerBI

### ISSUE THREAD

**Issue by josedavid-quero** [albertomorenogonzalez/FitnessGym#3]
En el documento no se indica ningún tipo de información que se vaya a visualizar en el informe ni cómo se va a acceder al mismo.

**Comment by albertomorenogonzalez** [comment]
En cuanto a como se debe acceder al mismo, debe ser desde la aplicación o simplemente se entrega el archivo y ya ?

**Comment by josedavid-quero** [comment]
Indicad, que se subirá al repositorio del proyecto y también se publicará en Power BI, compartiéndolo con la dirección de correo educativa del profesor.
jquesan535@m.educaand.es <-- esto no lo pongáis en la documentación

**Comment by josedavid-quero** [comment]
Buenos días, indicad lo del repositorio, por favor.
Tenéis que corregir el nombre del módulo, es Desarrollo de Interfaces, no Diseño de Interfaces.

**Comment by albertomorenogonzalez** [comment]
Okey, sin problema perdón por la tardanza
